export const sample = {
  data: [
    {
      width: 1920,
      height: 1080,
      backgroundColor: "#CBAAFF",
      backgroundUrl: "",
      duration: 5982,
      bg_musics: [
        {
          name: "lounging by moonlight",
          url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/music/lounging-by-moonlight-40.mp3",
          volume: "10%",
          id: "Kc4hsbtJoUA-9_84Y9Q3M",
          data: {
            data: {
              type: "music",
              name: "lounging by moonlight",
              url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/music/lounging-by-moonlight-40.mp3",
            },
          },
          start_time: 0,
          end_time: 0,
          start_point: 0,
          end_point: 0,
        },
      ],
      voice: {
        voice_url:
          "https://drz0f01yeq1cx.cloudfront.net/1721791391640-5f92387b-1a4b-4909-8f40-2ce9f751b711-5252.mp3",
      },
      elements: [
        {
          id: "avatar",
          url: "https://static.website-files.org/assets/avatar/avatar/thumbnail/1716457024475-tristan_cloth1_20240522.webp",
          scale_x: 1,
          scale_y: 1,
          width: 498,
          height: 310,
          offset_x: 1657.84,
          offset_y: 925.11,
          angle: 0,
          opacity: 1,
          attributes: {
            flipX: false,
            flipY: false,
          },
          type: "avatar",
          layer_number: 0,
          avatar_id: "8gDzWnUzlODKXhrB6y7LP",
          start_time: 0,
          end_time: 5982,
        },
        {
          id: "ACLH3Nj-HKG1lJtnFM_nh",
          url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/emoji/emoji_love.png",
          scale_x: 1,
          scale_y: 1,
          width: 200,
          height: 200,
          offset_x: 618.32,
          offset_y: 537.1,
          angle: 0,
          opacity: 1,
          attributes: {
            flipX: false,
            flipY: false,
          },
          type: "image",
          layer_number: 1,
          start_time: 0,
          end_time: 5982,
        },
      ],
      ratio: "16:9",
      background: "#CBAAFF",
      avatarFrom: 2,
      videoUrl:
        "https://static.website-files.org/assets/avatar/avatar/thumbnail/1716457024475-tristan_cloth1_20240522.webp",
      objects: [
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 1657.84,
          top: 925.11,
          width: 498,
          height: 310,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: false,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "avatar",
            url: "https://drz0f01yeq1cx.cloudfront.net/1720145326559-1.png",
            avatar_id: "8gDzWnUzlODKXhrB6y7LP",
            avatar_type: 1,
          },
          id: "avatarENDczCSJnb7LPYRQmMkf1",
          src: "https://drz0f01yeq1cx.cloudfront.net/1720145326559-1.png",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 618.32,
          top: 537.1,
          width: 200,
          height: 200,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: false,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "image",
            url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/emoji/emoji_love.png",
          },
          id: "ACLH3Nj-HKG1lJtnFM_nh",
          src: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/emoji/emoji_love.png",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 962.9,
          top: 542.9,
          width: 1080,
          height: 1080,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "avatar",
            url: "https://static.website-files.org/assets/avatar/avatar/content/1716457024475-tristan_cloth1_20240522.webp",
            avatar_id: "tristan_cloth1_20240522",
            avatar_type: 1,
          },
          id: "avatarfqOVG5h4k0TsEhtNRTxlr",
          src: "https://static.website-files.org/assets/avatar/avatar/content/1716457024475-tristan_cloth1_20240522.webp",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "textbox",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 215.83,
          top: 56.44,
          width: 415.08,
          height: 103.96,
          fill: "#FFC700",
          stroke: "#FFFFFF",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Anton-regular",
          fontWeight: "normal",
          fontSize: 92,
          text: "Goodhealth",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          data: {
            fontURL:
              "https://d11fbe263bhqij.cloudfront.net/public/Fonts/Anton/Anton-Regular.ttf",
            type: "text",
          },
          id: "rlTX3UykPVKuc4CXhFhg3",
        },
      ],
      sourceImage:
        "https://drz0f01yeq1cx.cloudfront.net/1720681923439-e8766e88-2515-4025-9c68-9888959ece86-4499.jpg",
    },
    {
      width: 1920,
      height: 1080,
      backgroundColor: "#CBAAFF",
      backgroundUrl: "",
      duration: 5982,
      bg_musics: [
        {
          name: "lounging by moonlight",
          url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/music/lounging-by-moonlight-40.mp3",
          volume: "10%",
          id: "Kc4hsbtJoUA-9_84Y9Q3M",
          data: {
            data: {
              type: "music",
              name: "lounging by moonlight",
              url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/music/lounging-by-moonlight-40.mp3",
            },
          },
          start_time: 0,
          end_time: 0,
          start_point: 0,
          end_point: 0,
        },
      ],
      voice: {
        voice_url:
          "https://drz0f01yeq1cx.cloudfront.net/1721791391640-5f92387b-1a4b-4909-8f40-2ce9f751b711-5252.mp3",
      },
      elements: [
        {
          id: "avatar",
          url: "https://static.website-files.org/assets/avatar/avatar/thumbnail/1716457024475-tristan_cloth1_20240522.webp",
          scale_x: 1,
          scale_y: 1,
          width: 1080,
          height: 1080,
          offset_x: 962.9,
          offset_y: 542.9,
          angle: 0,
          opacity: 1,
          attributes: {
            flipX: false,
            flipY: false,
          },
          type: "avatar",
          layer_number: 0,
          avatar_id: "tristan_cloth1_20240522",
          start_time: 5981.3,
          end_time: 9758.9,
        },
        {
          id: "rlTX3UykPVKuc4CXhFhg3",
          scale_x: 1,
          scale_y: 1,
          width: 415.08,
          height: 103.96,
          offset_x: 215.83,
          offset_y: 56.44,
          angle: 0,
          opacity: 1,
          attributes: {
            flipX: false,
            flipY: false,
          },
          type: "textbox",
          text: "Goodhealth",
          layer_number: 1,
          imageUrl: "",
          start_time: 5981.3,
          end_time: 9758.9,
        },
      ],
      ratio: "16:9",
      background: "#CBAAFF",
      avatarFrom: 2,
      videoUrl:
        "https://static.website-files.org/assets/avatar/avatar/thumbnail/1716457024475-tristan_cloth1_20240522.webp",
      objects: [
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 1657.84,
          top: 925.11,
          width: 498,
          height: 310,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: false,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "avatar",
            url: "https://drz0f01yeq1cx.cloudfront.net/1720145326559-1.png",
            avatar_id: "8gDzWnUzlODKXhrB6y7LP",
            avatar_type: 1,
          },
          id: "avatarENDczCSJnb7LPYRQmMkf1",
          src: "https://drz0f01yeq1cx.cloudfront.net/1720145326559-1.png",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 618.32,
          top: 537.1,
          width: 200,
          height: 200,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: false,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "image",
            url: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/emoji/emoji_love.png",
          },
          id: "ACLH3Nj-HKG1lJtnFM_nh",
          src: "https://d11fbe263bhqij.cloudfront.net/agicontent/avatar/elements/emoji/emoji_love.png",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "image",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 962.9,
          top: 542.9,
          width: 1080,
          height: 1080,
          fill: "rgb(0,0,0)",
          stroke: null,
          strokeWidth: 0,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          cropX: 0,
          cropY: 0,
          data: {
            type: "avatar",
            url: "https://static.website-files.org/assets/avatar/avatar/content/1716457024475-tristan_cloth1_20240522.webp",
            avatar_id: "tristan_cloth1_20240522",
            avatar_type: 1,
          },
          id: "avatarfqOVG5h4k0TsEhtNRTxlr",
          src: "https://static.website-files.org/assets/avatar/avatar/content/1716457024475-tristan_cloth1_20240522.webp",
          crossOrigin: "anonymous",
          filters: [],
        },
        {
          type: "textbox",
          version: "5.3.0",
          originX: "center",
          originY: "center",
          left: 215.83,
          top: 56.44,
          width: 415.08,
          height: 103.96,
          fill: "#FFC700",
          stroke: "#FFFFFF",
          strokeWidth: 2,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 8,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "Anton-regular",
          fontWeight: "normal",
          fontSize: 92,
          text: "Goodhealth",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "center",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline",
          minWidth: 20,
          splitByGrapheme: false,
          data: {
            fontURL:
              "https://d11fbe263bhqij.cloudfront.net/public/Fonts/Anton/Anton-Regular.ttf",
            type: "text",
          },
          id: "rlTX3UykPVKuc4CXhFhg3",
        },
      ],
      sourceImage:
        "https://drz0f01yeq1cx.cloudfront.net/1720681923439-e8766e88-2515-4025-9c68-9888959ece86-4499.jpg",
    },
  ],
  duration: 19.722375,
  draftId: false,
};
